basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: vrrrr227@gmail.com
    name: API Support
  description: This is a sample server for a bookstore.
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
  termsOfService: http://example.com/terms/
  title: Bookstore API
  version: "1.0"
paths: {}
swagger: "2.0"
